# Generated by Django 6.0.2 on 2026-04-22 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0011_finding_confidence_finding_evidence_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='analysis_type',
            field=models.CharField(blank=True, choices=[('static', 'Static Analysis'), ('dynamic', 'Dynamic Analysis'), ('manual', 'Manual')], default='', max_length=16),
        ),
    ]
